// vue2-quiz-vanilla/src/App.vue
<template>
  <div id="root">
    <Header />
    <div class="main">
      <router-view />
    </div>
    <Footer />
  </div>
</template>

<script>
import Header from "./components/Header.vue";
import Footer from "./components/Footer.vue";

export default {
  name: "QuizApp",
  components: {
    Header,
    Footer,
  },
};
</script>

<style lang="scss">
@import url("./assets/styles.scss");
</style>

// react-quiz-vanilla/src/App.js
import React from 'react';
import './App.scss';

import Header from './components/Header/Header';
import Footer from './components/Footer/Footer';
import Main from './components/Main/Main';

import { GlobalProvider } from './context/GlobalContext';

const App = () => {
  return (
    <GlobalProvider>
      <Header />
      <Main />
      <Footer />
    </GlobalProvider>
  );
}

export default App;
