// vue2-quiz-vanilla/src/views/Summary.vue
<template>
  <div className="review">
    <p>You got 1 of 3</p>
    <h2>All done!</h2>
    <p>You finished the quiz on difficulty.</p>
    <button className="start-over">Start Over</button>
  </div>
</template>

<script>
import { mapGetters, mapState, mapActions } from "vuex";

export default {
  name: "Summary",
  components: {},
  computed: {
    ...mapState([]),
    ...mapGetters([]),
  },
  methods: {
    ...mapActions([]),
  },
};
</script>

// react-quiz/src/components/Summary/Summary.tsx
import React, { useContext } from 'react';
import { GlobalContext } from '../../context/GlobalContext';
import { AppStateEnum } from '../../utils/enums';
import './Summary.scss';

const Summary: React.FC = () => {
  const {setAppState, userInfo, userScore} = useContext(GlobalContext);
  const {numberOfQuestions, difficulty} = userInfo


  const restart = () => {
    setAppState(AppStateEnum.welcome);
  }

  return (
    <div className="review">
      <p>You got {userScore} of {numberOfQuestions}</p>
      <h2>All done!</h2><p>You finished the quiz on {difficulty}.</p>
      <button className="start-over" onClick={() => restart()}>Start Over</button>
    </div>
  );
}

export default Summary;
