// vue2-quiz-vanilla/src/views/Quiz.vue
<template>
  <div class="intro">
    <article class="question-wrapper" v-if="allQuestions">
      <div class="question-area">
        <p>
          <strong>
            Question {{ questionIndex + 1 }} of {{ questions.length }}
          </strong>
        </p>
        <p class="question">{{ currentQuestion.question }}</p>
      </div>
      <div class="answers-wrapper">
        <p><strong>Possible Answers</strong></p>
        <div class="possible-answers">
          <label
            class="possible-answer"
            v-for="(answer, index) in currentQuestion.possibleAnswers"
            :key="answer"
          >
            <input
              type="radio"
              name="answer"
              :value="answer"
              v-model="selectedAnswer"
            />
            <span>{{ index + 1 }} </span>
            <span>{{ answer }}</span>
          </label>
        </div>
        <button class="next-btn" @click="next">Next Question</button>
      </div>
    </article>
  </div>
</template>

<script>
import { mapGetters, mapState, mapActions } from "vuex";

export default {
  name: "Quiz",
  components: {},
  data() {
    return {
      selectedAnswer: null,
    };
  },
  created() {
    if (!this.allQuestions.length) {
      this.$router.push({ name: "Home" });
    }
  },
  computed: {
    ...mapState(["allQuestions", "questionIndex", "userScore"]),
    ...mapGetters(["questions", "currentQuestion"]),
  },

  methods: {
    ...mapActions(["checkAnswer", "nextQuestion"]),
    next() {
      if (!this.selectedAnswer) {
        console.log("gotta choose an aswer");
        return;
      }
      this.checkAnswer(this.selectedAnswer);
      this.nextQuestion();
      this.selectedAnswer = null;
    },
    updateAnswer(e) {
      console.log(e.target.value);
    },
  },
};
</script>

// react-quiz/src/views/Quiz.tsx
import React, { useContext } from 'react'
import { useHistory } from 'react-router'
import { Link } from 'react-router-dom';
import { QuestionsContext } from '../App'
import { PossibleAnswer } from '../components/PossibleAnswer';
import { QuizHeader } from '../components/QuizHeader';

export const Quiz = (props: any) => {
  let history = useHistory();

  const index = +props.match.params.index
  const nextQuestionIndex = index + 1;
  const questions = useContext(QuestionsContext)
  const question = questions[index];

  if (!questions.length || !question) {
    history.push({
      pathname: '/welcome'
    });
    return null;
  }
  return (
    <div className="question-wrapper">
      <QuizHeader question={question.question} index={index + 1} total={questions.length} />
      <div className="answers-wrapper">
        <p><strong>Possible Answers</strong></p>
        <div className="possible-answers">
          {question.possibleAnswers.map((answer, index) => (
            <PossibleAnswer key={answer} answer={answer} index={index} />
          ))}
        </div>
        <Link
          className="next-btn"
          to={{
            pathname: `/quiz/${nextQuestionIndex}`,
          }}
        >Next Question</Link>
        {/* <button className="next-btn" onClick={() => nextQuestion()}>Next Question</button> */}
      </div>
    </div>
  )
}
